-- Migration script: Convert from old schema to new EERD schema
-- Preserves all data from Customers, Rentals, Vehicles tables
-- Transforms from: Customers, Rentals, Vehicles
-- To: Person, Employee, Customer, Rentals, Vehicles

SET FOREIGN_KEY_CHECKS = 0;

-- Step 1: Preserve data from tables that will be recreated
CREATE TABLE IF NOT EXISTS `backup_Vehicles` LIKE `Vehicles`;
INSERT INTO `backup_Vehicles` SELECT * FROM `Vehicles`;

CREATE TABLE IF NOT EXISTS `backup_Rentals` LIKE `Rentals`;
INSERT INTO `backup_Rentals` SELECT * FROM `Rentals`;

-- Step 2: Create new table structure (Person, Employee, Customer)
CREATE TABLE IF NOT EXISTS `Person` (
  `personID` varchar(36) NOT NULL,
  `first_name` varchar(45) NOT NULL,
  `middle_initial` varchar(45) DEFAULT NULL,
  `last_name` varchar(45) NOT NULL,
  `suffix` varchar(45) DEFAULT NULL,
  `email` varchar(100) NOT NULL,
  PRIMARY KEY (`personID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `Employee` (
  `personID` varchar(36) NOT NULL,
  `password` varchar(97) NOT NULL,
  PRIMARY KEY (`personID`),
  CONSTRAINT `employee_person_fk` FOREIGN KEY (`personID`) REFERENCES `Person` (`personID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `Customer` (
  `personID` varchar(36) NOT NULL,
  PRIMARY KEY (`personID`),
  CONSTRAINT `customer_person_fk` FOREIGN KEY (`personID`) REFERENCES `Person` (`personID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Step 3: Migrate Customers data to new structure
-- personID = customerID (UUID generated by application)
-- middle_name becomes middle_initial
INSERT INTO `Person` (`personID`, `first_name`, `middle_initial`, `last_name`, `suffix`, `email`)
SELECT `customerID`, `first_name`, `middle_name`, `last_name`, `suffix`, `email`
FROM `Customers`;

INSERT INTO `Employee` (`personID`, `password`)
SELECT `customerID`, `password`
FROM `Customers`;

INSERT INTO `Customer` (`personID`)
SELECT `customerID`
FROM `Customers`;

-- Step 4: Recreate Rentals table with new structure and migrate data
-- Changes: customerID -> personID, reference Customers -> Customer
DROP TABLE IF EXISTS `Rentals`;
CREATE TABLE `Rentals` (
  `rentalID` int NOT NULL AUTO_INCREMENT,
  `personID` varchar(36) NOT NULL,
  `vehicleID` int NOT NULL,
  `rental_date` date NOT NULL,
  `planned_return_date` date NOT NULL,
  `return_date` date DEFAULT NULL,
  `total_cost` decimal(10,2) NOT NULL,
  PRIMARY KEY (`rentalID`),
  KEY `rental-customer_idx` (`personID`),
  KEY `rental-vehicle_idx` (`vehicleID`),
  CONSTRAINT `rental-customer` FOREIGN KEY (`personID`) REFERENCES `Customer` (`personID`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `rental-vehicle` FOREIGN KEY (`vehicleID`) REFERENCES `Vehicles` (`vehicleID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Migrate rental data: map old customerID to new personID via Customer table
INSERT INTO `Rentals` (`rentalID`, `personID`, `vehicleID`, `rental_date`, `planned_return_date`, `return_date`, `total_cost`)
SELECT 
  r.`rentalID`,
  c.`personID`,
  r.`vehicleID`,
  r.`rental_date`,
  r.`planned_return_date`,
  r.`return_date`,
  r.`total_cost`
FROM `backup_Rentals` r
JOIN `Customer` c ON r.`customerID` = c.`personID`;

-- Step 5: Restore Vehicles table (structure unchanged, so direct restore)
DROP TABLE IF EXISTS `Vehicles`;
CREATE TABLE `Vehicles` LIKE `backup_Vehicles`;
INSERT INTO `Vehicles` SELECT * FROM `backup_Vehicles`;

-- Step 6: Clean up backup tables
DROP TABLE IF EXISTS `backup_Vehicles`;
DROP TABLE IF EXISTS `backup_Rentals`;

-- Step 7: Optional: Drop old Customers table after verification
-- Uncomment the following line after verifying data migration was successful
-- DROP TABLE `Customers`;

-- Verification queries (uncomment to run):
-- SELECT 
--   'Customers' AS table_name, COUNT(*) AS row_count FROM `Customers` UNION ALL
--   SELECT 'Person', COUNT(*) FROM `Person` UNION ALL
--   SELECT 'Employee', COUNT(*) FROM `Employee` UNION ALL
--   SELECT 'Customer', COUNT(*) FROM `Customer` UNION ALL
--   SELECT 'Rentals', COUNT(*) FROM `Rentals` UNION ALL
--   SELECT 'Vehicles', COUNT(*) FROM `Vehicles`;

SET FOREIGN_KEY_CHECKS = 1;